[package]
name = "xdg-desktop-portal-verdi"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Federico Maria Morrone <contact@morrone.dev>"]
readme = "README.md"
repository = "https://github.com/verdiwm/xdg-desktop-portal-verdi"
publish = false

[dependencies]
